language: groovy
jdk:
- oraclejdk8
sudo: false
cache:
    directories:
    - $HOME/.gradle

addons:
    apt:
        packages:
            - oracle-java8-installer

# Shell nop (install handled by gradle dependency management, no need to first assemble and then test)

install: ":"
before_script:
- export GRADLE_OPTS='-Dorg.gradle.daemon=false'
- chmod +x gradlew
script: "./gradlew test --info"
deploy:
  provider: releases
  api_key:
    secure: vho6lUj1sCwUvbPojgT6QO7j5SOhHRt6IeyKkAosLbxFWHqgBtEW5XxNBwMhtVE9Wczvip3suTpP6MvrschQpTl1JRaOZBrLXUTrESN6Ih3+lFyqCFOvc6/AxySvvxqSEQXnnEHdpMm4LaEuabYsbo25xqTjXCTHmLynvYJcKYo=
  file: dist/brainduck.jar
  on:
    repo: Zomis/Brainduck
