language: groovy

jdk:
    - oraclejdk8

# Use container build
sudo: false

cache:
    directories:
    - $HOME/.gradle

addons:
    apt:
        packages:
            - oracle-java8-installer

# Shell nop (install handled by gradle dependency management, no need to first assemble and then test)
install: ":"

before_script:
    # Gradle daemon won't add any benefit since Travis builds are always from scratch
    - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
    - chmod +x gradlew

script: "./gradlew test --info"
